### ISSUE TITLE
Required memory for data_split.py on Rao2014 data

### ISSUE THREAD

**Issue by ekokrek** [kimmo1019/hicGAN#2]
Hey there,

Currently, I am trying to reproduce your work with Rao2014 GM12878 data. 
However,at the stage where we preprocess and normalize the data and split it using data_split.py, the process gets killed due to excessive memory requirement. 
I work on a workstation with 64gb RAM. 
I am wondering on what memory specs did you convey this analysis? 

The article states the used GPU cards but not the required memory. 

Thanks in advance!

**Comment by kimmo1019** [comment]
Hi,
As others also complain to me about the memory usage of my code. I think the reason is that I loaded both high and low-resolution data of the whole genome into two dicts.  This may require too much memory, I did not consider this when I release the code, so sorry for that. One thing you can do is to generate low-resolution and high-resolution matrices by yourself. E.g., you can generate two matrix with size (N,40,40,1) , and skip data_split.py for data preprocessing, training with hicGAN directly.

**Comment by kimmo1019** [comment]
Hi, I just tested my code data_split.py with K562 data from Rao2014 et al. It indeed requires large memory, which is really a problem for users with limited resources. 

So I just reconstructed the code in data_split.py. 
1) Use sparse matrix to store high/low resolution hic contacts
2) Generate training data chromosome by chromosome

Now it is memory-friendly, only consumes less than 2 Gb in my test.

**Comment by ekokrek** [comment]
Hello There,

thank you for the reply. Indeed I saw that as a cause of large memory requirement and prepared my own input by modifying your code.

However, now at the prediction step for a a single chromosome (Chr12 in this case) I have again a similar problem of insufficient memory. I tested the code on a computer with 128GB RAM. 

What would be a solution for that ? 

The error message I receive is sth like this:


```
2020-07-14 13:25:09.657461: W tensorflow/core/framework/allocator.cc:124] Allocation of 45871358976 exceeds 10% of system memory.
2020-07-14 13:25:20.622053: W tensorflow/core/framework/allocator.cc:124] Allocation of 45871358976 exceeds 10% of system memory.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

```

**Comment by kimmo1019** [comment]
Hi ekokrek,
If you construct a whole matrix of a chromosome, it will consume much memory.
I would suggest you can divide the matrix of a whole chromosome into many small matrices and predict in a batch manner.
Then reconstruct the predicted matrices by youself.
If you have further problems, I'm happy to discuss and help you.
--Qiao
